Dynamo DB as Cache

diff --git a/.github/actions/setup_test_environment/action.yml b/.github/actions/setup_test_environment/action.yml
--- a/.github/actions/setup_test_environment/action.yml
+++ b/.github/actions/setup_test_environment/action.yml
@@ -59,6 +59,12 @@ runs:
         choco install --no-progress -y awscli
         echo "$PATH;C:\Program Files\Amazon\AWSCLIV2" >> $GITHUB_PATH
 
+    - name: Check AWS
+      shell: bash
+      run: |
+        aws sts get-caller-identity || echo "Failed to get AWS identity"
+        aws s3 ls || echo "Failed to list S3 buckets"
+
     - name: Download and Unpack Artifacts
       shell: bash
       env:
@@ -68,9 +74,6 @@ runs:
         FETCH_ARTIFACT_ARGS: ${{ inputs.FETCH_ARTIFACT_ARGS }}
         GITHUB_TOKEN: ${{ github.token }}
         IS_PR_FROM_FORK: ${{ inputs.IS_PR_FROM_FORK }}
-        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-east-2
       run: |
         python ./build_tools/install_rocm_from_artifacts.py \
           --run-id=${ARTIFACT_RUN_ID} \
